[server]
pythonVersion = "3.11"

[theme]
base="dark"
primaryColor="#4f46e5"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1e293b"
textColor="#f8fafc"

[client]
# Tampilkan toolbar (titik 3) supaya user bisa ganti theme
toolbarMode = "auto"

[browser]
gatherUsageStats = false
